# Generated by Django 4.2.3 on 2023-08-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
