# Generated by Django 4.2.3 on 2023-08-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0003_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='story',
            field=models.TextField(blank=True),
        ),
    ]
